### PR TITLE
Bring over HPACK implementation from Mint, rename to HPax

### PR DESCRIPTION
**Pull request by mtrudel**
This brings over the HPACK code & associated configuration / tests from the Mint project into this project

* Project named `HPax` (changed from `Hpax` as originally built).
* Code brought over unchanged, with just `s/Mint.HTTP2.HPACK/HPax/` having been applied
* `@moduledoc` for `HPax` was added
* Minor error in documentation example for `HPax.encode/2` corrected
* README usage examples are net-new
* CI Badge set up to point to Travis repo (untested, as I do not own this repo on Travis)
* Github CI is green. Happy to update badging to point there, and to consider GitHub CI as canon in lieu of Travis
* Hex badges / documentation links are set up assuming the package is published
* Copyright assigned as in the Mint repo

### CODE REVIEW

**Comment by mtrudel** [comment]
Of note, bandit's (fairly extensive) HPACK tests are green using this library. There remain two failing tests from h2spec's HPACK suite that I'll be pushing up as a separate PR.

**Comment by mtrudel** [comment]
Companion PR on the Mint repo is at https://github.com/elixir-mint/mint/pull/331

**Comment by whatyouhide** [comment]
@mtrudel haven't started reviewing yet, but since "HPACK" is all uppercase, I think we should call this "HPAX" (modules being `HPAX.<...>`. Can you make that change?

**Comment by whatyouhide** [comment]
Actually, I'm going ahead, merging this, and making just a few changes on my end 🙃

**Comment by mtrudel** [comment]
I’d thought about that, and here’s where I came to: HPACK the module was a literal reference to HPACK the standard, and so matching the casing made sense (the same way you’d call a module HTTP if it dealt with HTTP). HPax is a package name however, so its casing stands on its own. It’s the reason you didn’t name it MINT :). 

Not a strong opinion, just my 2c.

**Pull request merged**
